# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48bf6959f51f2dc37ef6b58ff7efad1e5fd219a8be21adbd068f0ba7488209a6feb28972ff83eda51bebde40d2b5e0e0ccde348628b5cc24161f260ac4c92e06

test:
  secret_key_base: 05a18c5637fcbf8fc831e80dadbdc7d74bc56e9e2570b1afabe93ddc7e2d40ae6ae19a93757e227852dcb464732ae7bd343d723ee08f563c1658ed8450ec5db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
