version: '3'
services:
  db:
    image: mysql:5.6
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ../db-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db
  web:
    tty: true
    stdin_open: true
    build: .
    container_name: app
    privileged: true
    volumes:
      - ../:/var/www/petshop
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - db